Add Support for Usernames
twitchdev/extensions-hello-world pull request #5
Opened 2018-04-08 00:52 UTC by fpruitt

## Purpose
Ideally, the 'Hello World' example for Twitch Extensions would match the patterns established in the Development Rig. This brings the initial startup in line with starting the Dev Rig by allowing users to specify their twitch username instead of having to grab the related ID's manually.

## What Does This Do?
* Adds a function that takes a given username and attempts to find the matching `owner_Id`
* Adds usage of the function, still exiting if an `owner_Id` cannot be found
* Maintains backwards compatibility for users still specifying `owner_Id` in env vars or on the command line. 
* Updates the README, removing copy about needing to manually lookup `owner_Id`. 
* Moves the line about needing an SSL cert to the top, so the user knows earlier to generate those (this temporarily tripped me up).

## Future Work
I would like to write tests for my additions, but it looks like there aren't any setup just yet and I assume the main maintainer would like to establish that pattern.

2018-05-02 00:05 UTC, Amorelandra commented
This is definitely something we need to do! Let's work on making this happen.

2018-05-02 00:07 UTC, Amorelandra commented on services/backend.js
> +    ownerId_retreival_error: "Failed to find a Twitch profile for the ownerName %s",
Thank you for adding the appropriate strings! I think there's typo here in the word 'retrieval' here. Would you mind fixing? Thanks!

2018-05-02 00:50 UTC, fpruitt commented
@Amorelandra fixed the spelling issue!

2019-01-30 22:48 UTC, Tenchumaru requested changes
Hi, Forrest. I like this and I'd like to merge it. I agree it's inconvenient to have to get the owner ID manually. I have three requests.

1. Include owner name as an option alongside of owner ID instead of replacing it. The code will accept either.
2. Remove language about generating SSL certificates. The Developer Rig no longer requires them.
3. Update to the current master. This pull request's branch is stale.

2020-11-23 21:32 UTC, closed without merging